// Copyright (c) Matthias Wolf, Mawosoft.

using System;

namespace DemoLib;

internal static class Program
{
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static int Main(string[] args)
    {
        bool addCoverlet = true;
        bool isServerMode = false;
        foreach (var arg in args)
        {
            if (arg.Length < 7 || arg[0] != '-') continue;
            var span = arg.AsSpan().Slice(arg[1] == '-' ? 2 : 1);
            // Collector args already present or called via dotnet test.
            if (span is "coverlet" or "coverage" or "dotnet-test-pipe")
            {
                addCoverlet = false;
                break;
            }
            if (span is "server")
            {
                // Server mode is used by Visual Studio and dotnet test. The latter is excluded above.
                isServerMode = true;
            }
        }
        if (addCoverlet && isServerMode
            && Environment.GetEnvironmentVariable("VSLANG") is not null // Always set inside Visual Studio.
            && Environment.GetEnvironmentVariable("VSTEST_BACKGROUND_DISCOVERY") is null // Exclude test discovery.
            && Environment.GetEnvironmentVariable("CODE_COVERAGE_FLAGS") is null) // Exclude IDE coverage analysis.
        {
            // The checks above are not perfect. Visual Studio sometimes runs test discovery without setting
            // VSTEST_BACKGROUND_DISCOVERY, e.g. if a test run is started and the build is out-of-date.
            // The only hint is that TESTINGPLATFORM_EXPERIMENTAL_VSTEST_RUNSETTINGS contains
            // <MaxCpuCount>0</MaxCpuCount> in such a case. But that also happens if "Run Tests in Parallel
            // is enabled in the Test Explorer.
            args = ["--coverlet", .. args];
        }
        //// Call the proper test host entry point. 
        //// return MicrosoftTestingPlatformEntryPoint.Main().GetAwaiter().GetResult();
        return AutoGenerated.XunitAutoGeneratedEntryPoint.Main(args);
    }
}
